# Site settings
title: E-Mail-Verschlüsselung
subtitle: Einfache Anleitung zum Austausch verschlüsselter E-Mails
description: Einfache Anleitung zum Austausch verschlüsselter E-Mails
baseurl: "/kryptomail/"
url: "https://svs.informatik.uni-hamburg.de" 
systems: [Windows, MacOS, Linux]
exclude: [screens]

# Build settings
markdown: kramdown
